### ISSUE TITLE
Wildcard characters on `entityNamesFilter` aren't working

### ISSUE THREAD

**Issue by JimDaly** [microsoft/PowerPlatform-DataverseModelBuilder#16]
People have also opened issues here [add support for trailing * to entityNamesFilter in pac modelbuilder](https://github.com/microsoft/powerplatform-build-tools/discussions/618)

The [Generate early-bound classes for the SDK for .NET](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/org-service/generate-early-bound-classes) incorrectly said this worked until today, but I've updated. it.

Understand that this depends on a way to apply `StartWith` filters on EntityMetadata.LogicalName values and no API supports this today.

**Comment by MattB-msft** [comment]
This is by design.  Only SDK Message filters support wild card search at this time.
