### ISSUE TITLE
[Feature Request] PAC ModelBuilder - Optionsets

### ISSUE THREAD

**Issue by AArndtDev** [microsoft/PowerPlatform-DataverseModelBuilder#7]
The CrmSvcUtil tool that many organizations used for many years to facilitate early bound code used to treat Optionsets as Optionsets and the Optionset cs file could be used with early bound code using supported CRM SDK techniques to set those fields. I would love a /legacyMode option in PAC ModelBuilder so that I could continue to code that way rather than massive refactoring to accommodate the newer enum structure. I would guess there are many organizations out there that also would benefit from being able to maintain proven and tested code without needing to change everything and re-test.

**Comment by daryllabar** [comment]
The EarlyBoundGenerator  supports an option to keep them as Option Sets, rather than typed enums.

**Comment by AArndtDev** [comment]
Hi Daryl, thanks for the reply! We have successfully used the /legacyMode option for CrmSvcUtil.exe, but couldn't find an equivalent for PAC ModelBuilder utility. We're running it with options specified on this page: https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/modelbuilder#pac-modelbuilder-build
